// Auth
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_DISMISS_ERROR = "AUTH_DISMISS_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const FETCH_PERFIL_START = "FETCH_PERFIL_START";
export const FETCH_PERFIL_SUCCESS = "FETCH_PERFIL_SUCCESS";
export const FETCH_PERFIL_FAIL = "FETCH_PERFIL_FAIL";
export const PERFIL_DISMISS_ERROR = "PERFIL_DISMISS_ERROR";

// Grupos
export const FETCH_GRUPOS_START = "FETCH_GRUPOS_START";
export const FETCH_GRUPOS_SUCCESS = "FETCH_GRUPOS_SUCCESS";
export const FETCH_GRUPOS_FAIL = "FETCH_GRUPOS_FAIL";
export const GRUPOS_DISMISS_ERROR = "GRUPOS_DISMISS_ERROR";
export const FETCH_ALL_GRUPOS_SUCCESS = "FETCH_ALL_GRUPOS_SUCCESS";

// App Theme
export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE";

// Id
export const ID_START = "ID_START";
export const ID_SETINICIAL = "ID_SETINICIAL";
export const ID_SETALL = "ID_SETALL";
export const ID_FAIL = "ID_FAIL";

export const ID_SETINSTRUMENTACIONES = "ID_SETINSTRUMENTACIONES";
// Temarios
export const FETCH_TEMARIOS_SUCCESS = "FETCH_TEMARIOS_SUCCESS";

// Materias
export const FETCH_MATERIAS_SUCCESS = "FETCH_MATERIAS_SUCCESS";

// Users
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
