export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_CURSOS_START = "FETCH_CURSOS_START";
export const FETCH_CURSOS_SUCCESS = "FETCH_CURSOS_SUCCESS";
export const FETCH_CURSOS_FAIL = "FETCH_CURSOS_FAIL";